# Generated by Django 3.2.8 on 2021-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211017_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
