# Generated by Django 3.2.8 on 2021-10-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_img.jpg', null=True, upload_to=''),
        ),
    ]
